pathToDataXML = "F:\\Projects\\Data\\Данные по скважинам\\Динамограммы\\bd"
pathToPickle = "F:\\Projects\\Data\\pickles"
pathToDataFromXML = pathToPickle + "\\dataFromXML.pickle"
pathToValuesSignals = pathToPickle + "\\valuesSignal.pickle"
pathToAmountValuesInSignal = pathToPickle + "\\amountValuesInSignal.pickle"
pathToMinMaxAmountValueInSignal = pathToPickle + "\\minMaxAmountValueInSignal.pickle"
